### ISSUE TITLE
Can't parse existing monerod config

### ISSUE THREAD

**Issue by iperrealistico** [everoddandeven/monerod-gui#8]
### Steps to reproduce

1. use monerod-gui portable on windows 11
2. open it
3. click import monerod config file (I am already running a node, I want to import my config file)
4. it gives a red error banner, cannot parse

### ✔️ Expected Behavior

should read the config

### 🔍 Additional context

windows 11
config file https://pastebin.com/raw/ESg2z9ER

**Comment by everoddandeven** [comment]
Thank you for reporting the issue, just fixed. The next release will contain the fix. :)
